- src/main/java/com/github/wasiqb/boyka/builders/ApiRequest.java
- src/main/java/com/github/wasiqb/boyka/builders/ApiResponse.java
- src/main/java/com/github/wasiqb/boyka/enums/ContentType.java
- src/main/java/com/github/wasiqb/boyka/enums/Messages.java
- src/main/java/com/github/wasiqb/boyka/enums/RequestMethod.java
- src/main/java/com/github/wasiqb/boyka/manager/ApiManager.java
- src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- src/main/java/com/github/wasiqb/boyka/utils/JsonParser.java
- src/test/java/com/github/wasiqb/boyka/testng/api/TestApi.java
- src/test/java/com/github/wasiqb/boyka/testng/api/requests/User.java
Introduced Builder class of ApiRequest to compose the request and executing the same via ApiManager.execute static method.
> :sparkles: Introduced Builder pattern in API

- .github/workflows/test.yml
- src/test/resources/test-config.json
- test-suites/testng-web-local.xml
Changed test job runner from Linux to Mac OS
> :wrench: Updated test workflow

- .github/workflows/test.yml
- src/main/java/com/github/wasiqb/boyka/actions/CommonActions.java
- src/main/java/com/github/wasiqb/boyka/actions/ElementFinder.java
- src/main/java/com/github/wasiqb/boyka/actions/KeyboardActions.java
- src/main/java/com/github/wasiqb/boyka/actions/VerifyDriverActions.java
- src/main/java/com/github/wasiqb/boyka/actions/VerifyElementActions.java
- src/main/java/com/github/wasiqb/boyka/builders/Locator.java
- src/main/java/com/github/wasiqb/boyka/enums/Browser.java
- src/main/java/com/github/wasiqb/boyka/enums/WaitStrategy.java
- src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- src/test/java/com/github/wasiqb/boyka/testng/web/TestWeb.java
- src/test/resources/test-config.json
- test-suites/testng-web-bs.xml
- test-suites/testng-web-grid.xml
- test-suites/testng-web-local.xml
- test-suites/testng-web.xml
- test-suites/testng.xml
Framework will wait until element is clickable before performing any action, and wait until element is visible before getting any element attributes.
> :sparkles: Added Auto-wait feature for UI

- .github/CODEOWNERS
- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/SUPPORT.md
- .github/pull_request_template.md
- .github/workflows/check-commit.yml
- .github/workflows/issue-labels.yml
- .gitignore
- src/test/java/com/github/wasiqb/boyka/testng/web/TestWeb.java
- src/test/java/com/github/wasiqb/boyka/testng/web/pages/ProductDetailsPage.java
Adding community standard files
> feat: Community files

- .github/workflows/test-java.yml
- .vscode/settings.json
- core-java/src/main/java/com/github/wasiqb/boyka/actions/KeyboardActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/CloudProviders.java
- core-java/src/test/resources/boyka-config.json
- core-java/test-suites/testng-web-lt.xml
> IMPORTANT: Make sure to check the `Allow edits from maintainers` box below this window
> feat(java): :sparkles: added LambdaTest support

- .gitignore
- .vscode/settings.json
- lerna.json
- package.json
- website/package.json
- yarn.lock
> chore(Internal): 🔖 changes made to auto generate changelogs

- .husky/pre-commit
- package.json
- website/docs/contributing/project-details/commit-steps.md
- website/docs/contributing/project-details/ready-your-pr.md
- website/src/css/custom.css
also fixed pre-commit hook and updated documentation accordingly
>
>
> - [x] Build command working …
> chore(Internal): :bug: fixed site theme inconsistency

- core-java/src/main/java/com/github/wasiqb/boyka/actions/DriverActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/WebSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/WindowResizeType.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- website/docs/api/web/actions/driver-actions.md
> feat(java): :triangular_flag_on_post: added window specifc methods

- core-java/pom.xml
- core-java/src/main/java/com/github/wasiqb/boyka/enums/Messages.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/ApiManager.java
> feat(java): :sparkles: add curl request in logging for better debugging and correcting enum message typo

- core-java/src/main/java/com/github/wasiqb/boyka/builders/ApiResponse.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/Messages.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/api/TestApi.java
- website/docs/api/api/builders/api-response.md
> feat(java): :sparkles: add method to verify header and  update documentation

- core-java/src/main/java/com/github/wasiqb/boyka/builders/ApiResponse.java
- core-java/src/main/java/com/github/wasiqb/boyka/builders/Locator.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/FrameworkSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/UISetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/Message.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/ApiManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/utils/ErrorHandler.java
- core-java/src/main/java/com/github/wasiqb/boyka/utils/JsonUtil.java
- core-java/src/main/java/com/github/wasiqb/boyka/utils/SettingUtils.java
- core-java/test-suites/testng-web-local-debug.xml
- website/docs/api/builders/api-response.md
- website/docs/api/manager/driver-manager.md
- website/docs/api/utils/error-handler.md
- website/docs/api/utils/json-util.md
- website/docs/api/utils/settings-util.md
- website/docs/api/utils/string-utils.md
> fix(java): :bug: fixed missing error handling

- .github/workflows/publish.yml
- .github/workflows/tweet-release.yml
- package.json
- website/package.json
- website/src/components/PageHero/index.tsx
- website/src/data/home-page.json
- yarn.lock
> fix(workflow): 💚 updated publish workflow and created release tweet workflow

- .husky/commit-msg
- .husky/pre-commit
commit lint will be checked first after that only other checks and tests will run
>
>
> - [ ] Build …
> fix(Internal): :bug: fixed pre-commit lint bug

- .github/workflows/check-commit.yml
- .github/workflows/codeql.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/test-java.yml
- core-java/src/main/java/com/github/wasiqb/boyka/actions/ElementFinder.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/web/theinternet/CheckboxTest.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/web/theinternet/DoubleClickTest.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/web/theinternet/pages/CheckboxPage.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/web/theinternet/pages/DoubleClickPage.java
also updated workflow to run on develop branch instead of main
>
>
> - [ ] Build command working …
> fix(java): :white_check_mark: added tests for few mouse actions

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
> feat(workflow): :construction_worker: created and pushed change log file when releasing main version

- .github/workflows/create-main-pr.yml
- .github/workflows/create-staging-pr.yml
> fix(workflow): :bug: fixed Error while creating PR

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/test-core.yml
> fix(workflow): :bug: fixed Error while preparing pre-release

- .github/workflows/create-main-pr.yml
- .github/workflows/create-staging-pr.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/test-core.yml
_This PR was generated via github actions workflow_
**Don't squash merge this PR**
<a href="https://gitpod.io/#https://github.com/WasiqBhamla/boyka-framework/pull/153"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🎉 PR: New Release candidate

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
> fix(workflow): :bug: fixed issue of empty version while releasing pre-release version

- .github/workflows/pre-release.yml
- .github/workflows/test-core.yml
> fix(workflow): :bug: fixed miscellaneous issues in workflows

- core-java/src/main/java/com/github/wasiqb/boyka/utils/JsonUtil.java
- core-java/src/test/java/com/github/wasiqb/boyka/testng/others/JsonUtilTest.java
> fix(java): :bug: fixed error while parsing non json response

- core-java/src/main/resources/log4j2.yml
> fix(java): :bug: updated the log4j2 xml to display info level logs in console

- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/WebSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/Message.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- core-java/src/main/resources/log4j2.yaml
- core-java/src/test/java/com/github/wasiqb/boyka/testng/others/DriverManagerTest.java
- core-java/src/test/resources/boyka-config.json
> fix(java): :bug: fixed errors when browser key is missing or empty in config

- .github/workflows/test-core.yml
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/mobile/device/DeviceSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/mobile/device/VirtualDeviceSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/mobile/server/ServerSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/DeviceType.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/DriverManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/ServiceManager.java
- core-java/src/test/resources/boyka-config.json
- core-java/test-suites/testng-mobile-bs.xml
- core-java/test-suites/testng-mobile-local.xml
- core-java/test-suites/testng-mobile.xml
- core-java/test-suites/testng-pr.xml
- core-java/test-suites/testng.xml
- website/docs/framework-docs/guides/configuration.md
- website/docs/framework-docs/guides/mobile/setup-config.md
> feat(java): :sparkles: added android browserstack support

- .github/workflows/create-main-pr.yml
- .github/workflows/create-staging-pr.yml
- .github/workflows/test-release.yml
- CHANGELOG.md
- core-java/pom.xml
- lerna.json
- sample-tests/src/test/resources/boyka-config.json
- website/package.json
_This PR was generated via github actions workflow_
**Don't squash merge this PR**
<a href="https://gitpod.io/#https://github.com/WasiqBhamla/boyka-framework/pull/215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(Internal): :bookmark: new release candidate

- sample-tests/pom.xml
- sample-tests/src/test/java/com/github/wasiqb/boyka/ui/EcommerceEndToEndTests.java
> fix(Internal): :bug: fixed compilation error in sample test

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/test-release.yml
> fix(workflow): :bug: fixed pre-release workflow issue

- .github/workflows/codesee-arch-diagram.yml
- README.md
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/mobile/server/ServerSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/web/WebSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/enums/TargetProviders.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/AndroidManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/IDriverManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/IOSManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/ServiceManager.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/WebDriverManager.java
- core-java/src/test/resources/boyka-config.json
- package.json
- website/docs/framework-docs/guides/configuration.md
- yarn.lock
> feat(java): :zap: simplified cloud configurations

- .github/workflows/release.yml
- README.md
- core-java/pom.xml
- core-java/src/main/java/com/github/wasiqb/boyka/actions/CommonActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/actions/elements/ClickableActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/actions/elements/ElementActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/actions/interfaces/elements/IElementActions.java
- core-java/src/main/java/com/github/wasiqb/boyka/config/ui/web/WebSetting.java
- core-java/src/main/java/com/github/wasiqb/boyka/manager/WebDriverManager.java
- core-java/src/test/resources/boyka-config.json
- package.json
- website/docs/api/actions/elements/clickable-actions.md
- website/docs/api/actions/elements/element-actions.md
- website/docs/framework-docs/guides/configuration.md
- yarn.lock
> fix(java): :bug: fixed issues in web automation

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- core-java/pom.xml
> fix(Internal): :bug: fixed release workflow to enable manual trigger

- .github/workflows/_create-pr.yml
- .github/workflows/_release.yml
- .github/workflows/_test-core-java.yml
- .github/workflows/create-develop-pr.yml
- .github/workflows/create-main-pr.yml
- .github/workflows/create-staging-pr.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/test-core.yml
- core-java/pom.xml
>
> - [ ] Copyright banner comment added to newly added files, except \`*.md\`, \`*.yml\`, \`*.json\`?
>
> IMPORTANT: Make sure to check the \`Allow …
> fix(workflow): :bug: fixed secret var issue in reusable workflows

- .github/dependabot.yml
- .github/workflows/deploy-site.yml
- .github/workflows/test-core.yml
> feat(Internal): :sparkles: updated dependabot config for grouped pr

- .github/workflows/release.yml
> fix(workflow): :bug: fixed issue in release workflow push-pom job

- .github/DISCUSSION_TEMPLATE/web.yml
- .github/ISSUE_TEMPLATE/bug.yml
- .github/pull_request_template.md
- core-java/pom.xml
- core-java/src/main/java/io/github/boykaframework/actions/elements/ClickableActions.java
- core-java/src/main/java/io/github/boykaframework/actions/elements/ElementActions.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/ecomm/AddCartTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/ecomm/pages/HomePage.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/jiomeet/JioMeetTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/saucedemo/SauceDemoTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/AlertsTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/CookiesTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/DoubleClickTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/DragDropTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/DropDownTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/FramesTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/LoginTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/WindowTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/wdio/WdioDemoTest.java
- core-java/test-suites/testng-web-local.xml
- package.json
> fix(java): :bug: fixed issue when clicking hovered element

- core-java/src/main/java/io/github/boykaframework/actions/api/ApiActions.java
- core-java/src/main/java/io/github/boykaframework/builders/ApiRequest.java
- core-java/src/main/java/io/github/boykaframework/enums/ContentType.java
- core-java/src/main/java/io/github/boykaframework/utils/StringUtils.java
- core-java/src/test/java/io/github/boykaframework/testng/api/postman/ApiPostmanTest.java
- core-java/src/test/resources/boyka-config.json
- core-java/test-suites/testng-mobile-lt.xml
- core-java/test-suites/testng-web-lt.xml
- package.json
- pnpm-lock.yaml
> fix(java): :bug: fixed issues in api form data request

- core-java/src/main/java/io/github/boykaframework/actions/elements/ElementActions.java
- core-java/src/main/java/io/github/boykaframework/actions/elements/TextBoxActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/elements/IElementActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/listeners/elements/IElementActionsListener.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/DropDownTest.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/pages/DropDownPage.java
- core-java/test-suites/testng-web-grid.xml
- core-java/test-suites/testng-web-local.xml
- package.json
- pnpm-lock.yaml
- website/package.json
> feat(java): :sparkles: added element list and dom property support

- .github/workflows/test-core.yml
- core-java/pom.xml
- core-java/src/main/java/io/github/boykaframework/actions/elements/FingerActions.java
- core-java/src/main/java/io/github/boykaframework/actions/elements/FingerGestureBuilder.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/elements/IFingerActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/listeners/elements/IFingerActionsListener.java
- core-java/src/main/java/io/github/boykaframework/config/ui/mobile/device/DeviceSetting.java
- core-java/src/main/java/io/github/boykaframework/manager/AndroidManager.java
- core-java/src/main/java/io/github/boykaframework/manager/IOSManager.java
- core-java/src/test/resources/boyka-config.json
- website/docs/api/actions/elements/finger-actions.md
- website/docs/framework-docs/guides/config/configuration.md
> feat(java): :sparkles: added longPress and doubleTap support for mobile

- package.json
- pnpm-lock.yaml
- website/docs/framework-docs/guides/config/configuration.md
> docs(website): :memo: updated the sample file in configuration document

- core-java/src/main/java/io/github/boykaframework/actions/CommonActions.java
- core-java/src/main/java/io/github/boykaframework/actions/elements/ClickableActions.java
- core-java/src/main/java/io/github/boykaframework/actions/elements/MouseActionBuilder.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/elements/IClickableActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/listeners/elements/IClickableActionsListener.java
- package.json
- pnpm-lock.yaml
- website/docs/api/actions/elements/clickable-actions.md
> feat(java): :zap: updated mouse related actions

- core-java/src/main/java/io/github/boykaframework/actions/drivers/DriverActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/drivers/IDriverActions.java
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/listeners/drivers/IDriverActionsListener.java
- core-java/src/test/java/io/github/boykaframework/testng/ui/theinternet/WindowTest.java
- package.json
- pnpm-lock.yaml
- website/docs/api/actions/drivers/driver-actions.md
- website/docs/api/actions/interfaces/listeners/drivers/driver-actions-listener.md
> feat(java): :sparkles: updated waitUntil method with timeout param

- core-java/src/main/java/io/github/boykaframework/builders/ApiRequest.java
- package.json
- pnpm-lock.yaml
> fix(java): :bug: fixed api credential interpolation issue

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/new-feature.yml
- .github/ISSUE_TEMPLATE/update-feature.yml
- .github/workflows/deploy-site.yml
- .github/workflows/release.yml
- core-java/src/test/java/io/github/boykaframework/testng/ui/lang/pages/HomePage.java
- core-java/src/test/resources/lang/gr.json
- package.json
- pnpm-lock.yaml
- website/package.json
> fix(java): :bug: fixed failing web test

- core-java/pom.xml
- core-java/src/main/java/io/github/boykaframework/actions/api/ApiActions.java
- core-java/src/main/java/io/github/boykaframework/builders/ApiResponse.java
- core-java/src/main/java/io/github/boykaframework/manager/ParallelSession.java
- core-java/src/test/java/io/github/boykaframework/testng/api/ssl/ApiSecurityTest.java
> fix(java): :bug: fix issue with latest OkHttp version upgrade

- core-java/pom.xml
- core-java/src/main/java/io/github/boykaframework/actions/interfaces/listeners/elements/IFingerActionsListener.java
- package.json
- pnpm-lock.yaml
> fix(java): :arrow_up: upgraded outdated dependencies
